import type { NextPage } from "next"
import Head from "next/head"
import Container from "../components/login/Container"

const Login: NextPage = () => {
    return (
        <div className="bg-indigo-400 h-screen">
            <Head>
                <title>Login</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="./lock.svg" />
            </Head>
            <Container />
        </div>
    )
}

export default Login
